Profile page
practicum-yandex/castle-rock pull request #11
Opened 2022-01-08 10:45 UTC by rsungatovich

2022-01-10 17:57 UTC, anastasiya-erenkova commented on src/components/FileLoaderWrapper/FileLoaderWrapper.view.tsx
> +            <CustomLabel htmlFor="avatar">
`htmlFor` и `id` не нужно использовать, когда используется конструкция
```
<label>
  <input />
</label>
```
В таком случае input и label уже будут связаны

2022-01-10 18:13 UTC, anastasiya-erenkova commented on src/pages/Profile/Profile.view.tsx
> +            <Title level={1}>{user?.display_name}</Title>
Кажется лучше сделать 
```
user?.display_name && <Title level={1}>{user?.display_name}</Title>
```
Иначе отображается пустой heading если нет display_name, при регистрации это поле не указывается, а значит оно не обязательно.
И думаю стоит использовать заголовок 2го уровня. На сколько мне известно семантически неверно использование более 1 заголовка 1го уровня на страницы. А он уже есть над навигацией

2022-01-10 18:16 UTC, anastasiya-erenkova commented on src/pages/Profile/Profile.styles.ts
> +        position: absolute;
Думаю лучше использовать fixed, поскольку нет гарантий, что какая-либо обертка выше не будет иметь значение свойства position в значении `relative` или `absolute`, а если такое случиться, то модальное окно будет выстраиваться уже по этой обертке, а не по странице целиком

2022-01-14 18:29 UTC, rsungatovich commented on src/components/FileLoaderWrapper/FileLoaderWrapper.view.tsx
> +            <CustomLabel htmlFor="avatar">
Точно, просто не убрал, писал код со соростью гепарда

2022-01-14 18:33 UTC, rsungatovich commented on src/pages/Profile/Profile.view.tsx
> +            <Title level={1}>{user?.display_name}</Title>
У нас же уровни заголовков прописаны исключительно для стилистических целей

2022-01-14 18:34 UTC, rsungatovich commented on src/pages/Profile/Profile.view.tsx
> +            <Title level={1}>{user?.display_name}</Title>
Чтобы удобнее было поддерживать дизайн на проекте

2022-01-14 18:35 UTC, rsungatovich commented on src/pages/Profile/Profile.view.tsx
> +            <Title level={1}>{user?.display_name}</Title>
Тогда такой подход с Title и указанием в нем семантических тегов, со строгим определением в нем font size не подходит

2022-01-14 18:35 UTC, rsungatovich commented on src/pages/Profile/Profile.view.tsx
> +            <Title level={1}>{user?.display_name}</Title>
Мы пишем spa приложение, так что забей)

2022-01-14 18:37 UTC, rsungatovich commented on src/pages/Profile/Profile.view.tsx
> +            <Title level={1}>{user?.display_name}</Title>
`user?.display_name && <Title level={1}>{user?.display_name}</Title>`

это поправил

2022-01-16 14:23 UTC, bercly0b commented on src/pages/Profile/Profile.view.tsx
> +    function changeAvatar(event: React.FormEvent) {
тут тоже самое что и в https://github.com/practicum-yandex/castle-rock/pull/8#discussion_r785446077
коллбеки было бы здорово обернуть в useCallback
а данные формы хранить и доставать из стейта реакта, а не из дома

2022-01-16 14:23 UTC, bercly0b requested changes
https://github.com/practicum-yandex/castle-rock/pull/11/commits/ca98b92bcc8642195cd5889fb08b98c93f13448e#r785448432

2022-01-16 15:48 UTC, merged