Redux Thunk
practicum-yandex/castle-rock pull request #14
Opened 2022-01-15 12:30 UTC by rsungatovich

2022-01-15 12:32 UTC, rsungatovich commented
Ответвлялся от ветки в которой добавил Redux, поэтому если смотреть изменения, то можно увидеть изменения и от ветки, в которой добавлял Redux.

2022-01-15 13:34 UTC, anastasiya-erenkova approved these changes

2022-01-16 14:18 UTC, bercly0b commented on package.json
> +    "redux-thunk": "2.4.1",
кроме установки надо бы еще подключить thunk и желательно написать какой то ассинхронный экшен. например получение юзера

2022-01-16 14:18 UTC, bercly0b requested changes
https://github.com/practicum-yandex/castle-rock/pull/14/commits/79ad974da7b6d18e68e8f885108823cc32b35357#r785447731

2022-01-16 15:56 UTC, rsungatovich commented on package.json
> +    "redux-thunk": "2.4.1",
Там просто для этого есть отдельная таска, я и сам не понял для чего это нужно было делить на две

2022-01-16 15:56 UTC, merged