Thunk Hooks for Auth page
practicum-yandex/castle-rock pull request #19
Opened 2022-01-22 11:19 UTC by rsungatovich

2022-01-22 11:40 UTC, anastasiya-erenkova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить в проект HOC или Hook для работы с авторизацией через Redux Thunk (или Redux Saga), Reselect и API.](https://trello.com/c/mMYBV3Ik/23-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82-hoc-%D0%B8%D0%BB%D0%B8-hook-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B5%D0%B9-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-redux-thunk-%D0%B8%D0%BB%D0%B8-redux-saga-reselect-%D0%B8-api)

2022-01-25 19:18 UTC, anastasiya-erenkova approved these changes

2022-01-26 15:16 UTC, bercly0b commented on src/pages/Auth/Auth.view.tsx
> +		dispatch(AuthService.signup(getFormValues(formEl), () => navigate("/", { replace: true })));
какой то не редаксовый флоу получился) 
обычно делают примерно примерно так
* функция экшен, которая ходит за данными, в нашем случае вызывает метод контроллера и диспатчит результат. она может выглядеть так:
    * задиспатчить экшен `начало загруки`
    * начать загруку 
    * задиспатчить успешное окончание загрузки с данными или неуспешную загрузку
    * [пример такого экшена](https://rajdee.gitbooks.io/redux-in-russian/content/docs/advanced/AsyncActions.html#%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D1%8D%D0%BA%D1%88%D0%B5%D0%BD%D0%BE%D0%B2)
* а в компоненте потом просто делается `dispatch(myAsyncAction)`

2022-01-26 15:17 UTC, bercly0b commented on src/pages/Auth/Auth.view.tsx
> +		dispatch(AuthService.signup(getFormValues(formEl), () => navigate("/", { replace: true })));
таким образом вся логика по запросу данных уезжает из компонента и в нем только остается диспатч экшена

2022-01-26 15:17 UTC, bercly0b requested changes
https://github.com/practicum-yandex/castle-rock/pull/19#discussion_r792744527

2022-01-30 11:33 UTC, rsungatovich commented on src/pages/Auth/Auth.view.tsx
> +		dispatch(AuthService.signup(getFormValues(formEl), () => navigate("/", { replace: true })));
Да я сам тоже нормально не разобрался как делать,
в теории практикума вообще информации нет особо как с этим работать

2022-01-30 11:33 UTC, merged