Leaderboard API
practicum-yandex/castle-rock pull request #25
Opened 2022-02-13 10:05 UTC by rsungatovich

2022-02-15 16:38 UTC, anastasiya-erenkova approved these changes

2022-02-15 16:39 UTC, anastasiya-erenkova commented on src/components/Login/Login.view.tsx
> +			console.log(data.service_id)
console.log нужно оставлять?

2022-02-17 13:55 UTC, bercly0b commented on src/components/Login/Login.view.tsx
> +			console.log(data.service_id)
наверное от дебага остались. надо бы убрать

2022-02-17 13:55 UTC, bercly0b commented on src/components/Login/Login.view.tsx
> +	const loginWithOAuth = () => {
useCallback был бы не лишним

2022-02-17 13:57 UTC, bercly0b commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = store.getState().board.item || []; // не сразу обновляется
а давай [селектор](https://react-redux.js.org/api/hooks#useselector) напишем?
что бы руками внутрь стейта не лезть. селектор кеширование умеет

2022-02-17 13:57 UTC, bercly0b commented on src/pages/Game/Game.view.tsx
> +	const user: UserData = store.getState().user.item; // не сразу обновляется
https://github.com/practicum-yandex/castle-rock/pull/25/files#r809074720

2022-02-17 14:00 UTC, bercly0b commented on src/services/BoardService.ts
> +        return (dispatch: any): void => {
почему `any`? в редаксе есть тип `Dispatch`
либо в thunk есть `ThunkDispatch`

2022-02-17 14:02 UTC, bercly0b commented on src/services/BoardService.ts
> +            .then((res) => dispatch(setBoard(res.data)))
мне не очень нравится, что тут сервис и логика экшена смешались.
мне кажется должно быть как то так.
- сервис просто ходит в сеть и отдает данные
- есть отдельный экшен, который получит из сервиса данные и задиспатчит их в редакс
- компонент для получения данных просто вызовет экшен

2022-02-17 14:03 UTC, bercly0b requested changes
пройдись по комментам пож

2022-02-19 12:11 UTC, rsungatovich commented on src/services/BoardService.ts
> +            .then((res) => dispatch(setBoard(res.data)))
не совсем понятно, как это должно выглядит в коде(

2022-02-19 12:12 UTC, rsungatovich commented on src/services/BoardService.ts
> +            .then((res) => dispatch(setBoard(res.data)))
я не доконца розобрался как реализуется правильный флоу с этими диспатчами и тд

2022-02-19 12:13 UTC, rsungatovich commented on src/components/Login/Login.view.tsx
> +			console.log(data.service_id)
Это да, сдкчайно попало сюда

2022-02-19 12:13 UTC, rsungatovich commented on src/components/Login/Login.view.tsx
> +	const loginWithOAuth = () => {
Это тоже, там все изменилось в другой ветке

2022-02-19 12:14 UTC, rsungatovich commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = store.getState().board.item || []; // не сразу обновляется
Можно оставить это на потом, если останется время на гуд практис

2022-02-19 12:15 UTC, rsungatovich commented on src/services/BoardService.ts
> +        return (dispatch: any): void => {
Эни шмэни)

2022-02-20 08:40 UTC, bercly0b commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = store.getState().board.item || []; // не сразу обновляется
ну вообще тут делов на 5 минут) 
наприсать селектор - это функция, которая принимает стейт и возвращает нужно значение.
и передать этот селектор в `useSelector`. примеры можно почитать в ссыке, которую я прикрепил выше
и все) и тогда из компонентов можно будет выпилить редаксовый контекст и поход руками в стейт

2022-02-20 09:24 UTC, bercly0b commented on src/services/BoardService.ts
> +            .then((res) => dispatch(setBoard(res.data)))
значит нужно разбираться) это важно.
у нас подключен redux-thunk, он [позволяет](https://github.com/reduxjs/redux-thunk#motivation) писать асинхронные экшены.
где то [в районе](https://github.com/practicum-yandex/castle-rock/blob/main/src/store/reducers/user.ts) стора (кстати там лучше редьюсер и экшены разнести на разные файлы), нужно написать асинхронный экшен, который использует сервис `BoardService` для получения данных, и потом задиспатчит эти данные в редьюсер и они появятся в стейте. 
а компонент просто будет смотреть на эту веточку стейта и когда там появятся данные, он перерендерится.
это называется разделение ответственности, каждый будет заниматься своим делом. сервисы не будут завязаны на редакс. их можно будет использовать не зависимо от реакта. например если мы захотим получить лидерборд на сервере, мы сможем просто переиспользовать этот же сервиc

вот диаграмма как должно выглядеть движение данных в редаксе. View - это компонент. 
<img width="494" alt="Screen Shot 2022-02-20 at 12 22 07" src="https://user-images.githubusercontent.com/29758632/154836182-85eddd9b-cf77-4544-a4a5-acff6b4ceda1.png">
[вот](https://habr.com/ru/post/246959/) не плохая статья про это

2022-02-20 09:32 UTC, bercly0b commented on src/services/BoardService.ts
> +            .then((res) => dispatch(setBoard(res.data)))
если рассуждать архитектурно:
`BoardService` - это сущность, которая ходит в сеть за данными лидерборда. зачем ей диспатч/редакс и почему она не может работать без этого?

2022-02-20 11:57 UTC, rsungatovich commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = store.getState().board.item || []; // не сразу обновляется
Пока сделал без всего этого, просто вынес их в функции. Я из предложения не понял, что ты имеешь ввиду.
Если тебе не трудно, пришли, пожалуйста, код реализации того что ты предлогаешь)

2022-02-20 11:59 UTC, rsungatovich commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = store.getState().board.item || []; // не сразу обновляется
Там сейчас есть баг (он был и до этого) - не перерендеривается компонент, когда приходят данные.

2022-02-21 07:32 UTC, bercly0b commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = store.getState().board.item || []; // не сразу обновляется
ну так из-за этого и баг, потому что тут нет подписки на стейт. 
если использовать селектор, то будет перерендер.
[урок про селекторы](https://practicum.yandex.ru/learn/middle-frontend/courses/102addf4-d18b-4cb1-bff5-918b417d3af1/sprints/18178/topics/05d6a84a-a8ef-44b8-bb02-6c8c8a6186ce/lessons/badf68d6-a953-4d5f-a5f2-ca488b00d36c/)
[дока про useSelector](https://react-redux.js.org/api/hooks#useselector)

2022-02-21 07:36 UTC, bercly0b commented on src/services/BoardService.ts
> +            .then((res) => cb(res.data))
а зачем тут коллбек? 
есть 3 основных способа работы с асинхонным кодом: промисы, async/await и коллбеки.
и миксовать эти способы - не очень хорошая практика.
раз уж начали писать сервис на промисах, пусть он будет просто возвращать промис с данными?

2022-02-21 07:37 UTC, bercly0b commented on src/services/BoardService.ts
> +            .then((res) => cb(res.data))
`static getBoard(body: BoardRequest): Promise<BoardMemberData[]>` то есть вот так должно получится

2022-02-21 07:37 UTC, bercly0b commented on src/services/BoardService.ts
> +            .then((res) => cb(res.data))
ну и соответственно остальные методы тоже по аналогии

2022-02-21 07:38 UTC, bercly0b commented on src/store/selectors/selectBoardList.ts
> +    return state.getState().board.item || [];
[вот](https://react-redux.js.org/api/hooks#useselector-examples) пример из доки, которую я уже несколько раз скинул, как должен выглядеть селектор. посмотри его пожалуйста

2022-02-21 07:40 UTC, bercly0b commented on src/store/selectors/selectBoardList.ts
> +    return state.getState().board.item || [];
`state !== store`
`state` это просто структура данных стейта, у него нет метода `getState`

2022-02-21 07:41 UTC, bercly0b commented on src/pages/Profile/Profile.view.tsx
> +	const user: UserData = selectUser(store); // не сразу обновляется
[useSelector](https://react-redux.js.org/api/hooks#useselector)

2022-02-21 07:41 UTC, bercly0b commented on src/pages/Board/Board.view.tsx
> +	const boardList: BoardMemberData[] = selectBoardList(store); // не сразу обновляется
[useSelector](https://react-redux.js.org/api/hooks#useselector)

2022-02-21 07:48 UTC, rsungatovich commented on src/services/BoardService.ts
> +            .then((res) => cb(res.data))
> а зачем тут коллбек? 
> есть 3 основных способа работы с асинхонным кодом: промисы, async/await и коллбеки.
> и миксовать эти способы - не очень хорошая практика.
> раз уж начали писать сервис на промисах, пусть он будет просто возвращать промис с данными? 

На курсе так учили на этом)

2022-02-21 07:49 UTC, rsungatovich commented on src/services/BoardService.ts
> +            .then((res) => cb(res.data))
Я знаю, что можно вернуть промис, и подписаться на него в другом месте.

2022-02-21 07:52 UTC, rsungatovich commented on src/services/BoardService.ts
> +            .then((res) => cb(res.data))
https://practicum.yandex.ru/learn/middle-frontend/courses/102addf4-d18b-4cb1-bff5-918b417d3af1/sprints/15457/topics/f859c50a-5f43-40e9-8b4a-e11743d5aa38/lessons/75b38a5a-399d-4fd6-89c2-688d709fb956/

2022-02-24 07:58 UTC, bercly0b commented on src/services/AuthService.ts
> +				.then(() => cb())
а тут че коллбеки не оторвал? промисы же)

2022-02-24 08:00 UTC, bercly0b commented on src/pages/Board/Board.view.tsx
> +	const boardList = useSelector<any, BoardMemberData[]>((state) => state.board.item) || [];
- почему `any`? у нас разве нет интерфейса для стейта? 
- селекторы лучше выносить в функции и использовать по ссылке, тогда внутри `useSelector` будет работать оптимизация. а в такой реализации на каждый ререндер в `useSelector` будет попадать новая функция
- `|| []` лучше внутрь селектора убрать

2022-02-24 08:00 UTC, bercly0b approved these changes

2022-02-26 16:29 UTC, merged