OAauth
practicum-yandex/castle-rock pull request #27
Opened 2022-02-19 12:08 UTC by rsungatovich

2022-02-19 16:09 UTC, anastasiya-erenkova commented on src/utils/http.ts
> +});
Пройди prettier'ом

2022-02-19 16:09 UTC, anastasiya-erenkova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить OAuth-авторизацию в проект.](https://trello.com/c/dE5wsr2K/31-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-oauth-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8E-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82)

2022-02-20 12:04 UTC, rsungatovich commented on src/utils/http.ts
> +});
Предлагаю пройтись преттиром сразу в ветке main - в других местах возможно тоже есть что поправить. 
Сделаю, когда уже смерджим все остальные ветки с этого спринта, ок? Создам таску на себя.

2022-02-20 12:04 UTC, rsungatovich commented on src/utils/http.ts
> +});
*ну или от ветки main создать ветку, и там пройтись, потом смерджить

2022-02-21 09:15 UTC, bercly0b commented on src/services/AuthService.ts
> +				.then(() => cb())
про коллбеки уже писал в соседней задаче. давай наверное там и поправим?

2022-02-21 09:19 UTC, bercly0b commented on src/pages/App/App.view.tsx
> +// Сделал так потому что useParams не работает в данном случае
потому что useParams не про это. он берет параметры из роута, а не гет параметры
[дока](https://reactrouter.com/docs/en/v6/api#useparams)

можно заиспользовать [готовый хук](https://reactrouter.com/docs/en/v6/api#useparams) для гет параметров, а лучше написать свой. потому что он вероятнее всего понадобится в других местах

2022-02-21 09:19 UTC, bercly0b requested changes
https://github.com/practicum-yandex/castle-rock/pull/27/files#r810921172

2022-02-21 16:58 UTC, rsungatovich commented on src/pages/App/App.view.tsx
> +// Сделал так потому что useParams не работает в данном случае
Ссылка на готовый хук ведет к useParams. Написать свой хук, это как? Я там написал свое реешение, оно работает.

2022-02-23 16:52 UTC, rsungatovich commented on src/pages/App/App.view.tsx
> +// Сделал так потому что useParams не работает в данном случае
Предлагаю оставить это на потом, чтобы можно было преступить к задачам 8-го спринта

2022-02-24 07:55 UTC, bercly0b commented on src/pages/App/App.view.tsx
> +// Сделал так потому что useParams не работает в данном случае
не ту ссылку вставил.
https://www.npmjs.com/package/use-query-params

2022-02-24 07:56 UTC, bercly0b approved these changes

2022-02-26 16:40 UTC, merged