Настройка SSR
practicum-yandex/castle-rock pull request #28
Opened 2022-02-19 15:48 UTC by anastasiya-erenkova

2022-02-19 15:49 UTC, anastasiya-erenkova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настроить Express для Server Side Rendering (без Redux, просто отдавать React-страничку).](https://trello.com/c/dHMXzUqK/28-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-express-%D0%B4%D0%BB%D1%8F-server-side-rendering-%D0%B1%D0%B5%D0%B7-redux-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE-%D0%BE%D1%82%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-react-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%BA%D1%83)

2022-02-20 15:19 UTC, rsungatovich approved these changes

2022-02-20 15:19 UTC, rsungatovich commented
Молорик, что разобралась со всем этим 👍

2022-02-21 09:20 UTC, bercly0b commented on README.md
> +- `npm run dev` - запуск режима разработки,
👍

2022-02-21 09:22 UTC, bercly0b commented on src/server/index.tsx
> +function makeHTMLPage(content: string) {
тут можно по файлам разнести, что бы все в индексе не лежало.
например так
- index файл
- роутер
- рендер страниц

2022-02-21 09:22 UTC, bercly0b commented on src/store/store.ts
>  	return store as any;
почему any? у нас разве не описан интерфейс стора?

2022-02-21 09:24 UTC, bercly0b commented on src/utils/useIsSsr.ts
> +	return isSsr;
в такой реализации при первом рендере на клиенте `isSsr` будет тоже `true`. и потом `useEffect` вызовет лишний ререндер и сделает переменную `false`
давай лучше [такое](https://stackoverflow.com/a/32598826) заиспользуем?

2022-02-21 09:25 UTC, bercly0b requested changes
в целом все ок, пару минорных замечаний. посмотри пож

2022-02-24 11:27 UTC, anastasiya-erenkova commented on src/server/index.tsx
> +function makeHTMLPage(content: string) {
✅

2022-02-24 11:27 UTC, anastasiya-erenkova commented on src/store/store.ts
>  	return store as any;
Нет, не описан

2022-02-24 11:27 UTC, anastasiya-erenkova commented on src/utils/useIsSsr.ts
> +	return isSsr;
✅

2022-02-26 10:27 UTC, merged