Login and registration pages
practicum-yandex/castle-rock pull request #8
Opened 2021-12-25 11:09 UTC by rsungatovich

2021-12-27 16:58 UTC, anastasiya-erenkova commented on src/components/Login/Login.styles.ts
> +        color: ${theme.colors.default()};
Color default задан всему тексту по дефолту в стилях App.styles.ts через body
По идее здесь не должно быть проблем и дополнительного указания цвета

2021-12-27 17:00 UTC, anastasiya-erenkova commented on src/components/Login/Login.styles.ts
> +        font-size: ${theme.headlines.h2};
Уже есть компонент Title который стилизует h1/2/3 и задает определенный font-size, стоит использовать его, вместо дублирования стилей
```
font-weight: bold;
line-height: 1em;
```
Можно добавить в этот компонент, чтобы эти стили были по умолчанию в компоненте заголовка (Title)

2021-12-27 17:02 UTC, anastasiya-erenkova commented on src/components/Login/Login.styles.ts
> +export const CustomButton = styled(Button)`
Я бы использовала нейминг наоборот `export const Button = styled(CustomButton )`
Чтобы во view был Button, иначе через приставки Custom труднее читать код

2021-12-27 17:03 UTC, anastasiya-erenkova commented on src/components/Registration/Registration.styles.ts
> +`;
Копипаста
Ссылку можно вынести в отдельный компонент

2021-12-27 17:03 UTC, anastasiya-erenkova commented on src/components/Registration/Registration.styles.ts
> +`;
И здесь копипаста
Можно сделать отдельный компонент Form и использовать его стилизованные элементы, как в компоненте Table

2021-12-27 17:04 UTC, anastasiya-erenkova commented on src/components/Registration/Registration.view.tsx
> +        type: 'email',
Тут наверное не email

2021-12-27 17:06 UTC, anastasiya-erenkova commented on src/components/Registration/Registration.view.tsx
> +                {FIELDS.map((field, index) =>
Рендер функцию можно вынести отдельно и использовать след образом
```
const renderInput = (field, index) => 
                    <CustomField 
                        key={index}
                        type={field.type}
                        label={field.placeholder}
                    />

...

{ FIELDS.map(renderInput) }

```

2021-12-27 17:08 UTC, anastasiya-erenkova commented on src/components/Registration/Registration.view.tsx
> +            <CustomLink href="#">Войти</CustomLink>
Думаю здесь вполне можно использовать компонент `Link` от react-router

2021-12-27 17:11 UTC, anastasiya-erenkova commented on src/pages/Auth/Auth.styles.ts
> +    height: 100vh;
В одном из PR я делала компонент Layout, который занимает минимальную высоту в 100vh и обернула все страницы (поскольку у нас меню отображается на всех страницах)

Ширину через 100vw лучше не задавать, поскольку если будет необходимость в большей высоте, то сбоку появиться скролл, а он тоже участвует в ширине и поэтому появиться еще и горизонтальный скролл, кажется здесь лучше использовать 100%

2021-12-28 12:01 UTC, rsungatovich commented on src/components/Login/Login.styles.ts
> +export const CustomButton = styled(Button)`
```
import React, { ButtonHTMLAttributes } from "react";
import { Component } from "@/utils/components";
import { CustomButton } from "./Button.styles";

type Props = ButtonHTMLAttributes<HTMLButtonElement>;

const Button: Component<Props> = (props) => <CustomButton {...props} />;

export default Button;
```

Я сделал аналогично кнопке, которую сделала ты)

2021-12-28 12:06 UTC, rsungatovich commented on src/components/Login/Login.styles.ts
> +export const CustomButton = styled(Button)`
```
export const CustomButton = styled(Button)`
    ${({ theme }) => `
        width: 100%;
        margin-bottom: ${theme.spacing(2)};
    `}
`
```

И как бы здесь добавляется уже добавляется компонент, который ты делала `styled(**Button**)`

2021-12-28 13:29 UTC, rsungatovich commented on src/components/Registration/Registration.view.tsx
> +                {FIELDS.map((field, index) =>
То что можно просто передать ссылку на функцию в качестве колбэка, это мне известно)
Выносить это как отдельную функцию, в данном случае действительно не обязательно.

Но все же, спасибо, за то что поделилась своим взглядом на то, как лучше организовать код

2021-12-28 13:29 UTC, rsungatovich commented on src/components/Registration/Registration.view.tsx
> +                {FIELDS.map((field, index) =>
То что можно просто передать ссылку на функцию в качестве колбэка, это мне известно)
Выносить это как отдельную функцию, в данном случае действительно не обязательно.

Но все же, спасибо, за то что поделилась своим взглядом на то, как лучше организовать код.

2022-01-10 17:18 UTC, anastasiya-erenkova commented on src/components/Login/Login.styles.ts
> +export const CustomButton = styled(Button)`
В кнопке так сделала, потому что дублировался нейминг. Нельзя сделать `const Button = <Button />`
А здесь предлагаю сделать
```
import CustomButton from "@/share/Button";

export const Button = styled(CustomButton)`
    ${({ theme }) => `
        width: 100%;
        margin-bottom: ${theme.spacing(2)};
    `}
`
```

Или можно назвать `ShareButton`

2022-01-10 17:27 UTC, anastasiya-erenkova commented on src/helpers/getFormValues.ts
> +    return elements.reduce((formValues, el) => {
По элементам формы с данными можно пройтись так
```
	for (const [name, value] of formData.entries()) {
		formValues[name] = value;
	}
	```
	
	Мне кажется это проще, чем фильтровать кнопку и проходиться по html элементам, а не по данным

2022-01-10 17:28 UTC, anastasiya-erenkova commented on src/helpers/getFormValues.ts
> +export function getFormValues(form: HTMLFormElement): any {
наверное возвращается FormValue, а не any

2022-01-10 17:33 UTC, anastasiya-erenkova commented on src/share/Layout/Layout.styles.ts
> +		height: 100vh;
А если содержимого будет больше чем вмещает экран по высоте?
Если не ошибаюсь, пользователь не увидит часть контента в таком случае

2022-01-14 18:01 UTC, rsungatovich commented on src/helpers/getFormValues.ts
> +    return elements.reduce((formValues, el) => {
Да, просто для этого нужно было расширить тс конфиг

2022-01-14 18:10 UTC, rsungatovich commented on src/share/Layout/Layout.styles.ts
> +		height: 100vh;
Правильно, но мы наверное будет ограничивать высоту, это же игра

2022-01-14 18:10 UTC, rsungatovich commented on src/share/Layout/Layout.styles.ts
> +		height: 100vh;
Если что потому уберем, еслит нужно будет

2022-01-16 14:03 UTC, bercly0b commented on src/pages/Auth/Auth.view.tsx
> +    function signup(event: FormEvent): void {
хорошо бы  `useCallback` завернуть. и `signin` тоже

2022-01-16 14:05 UTC, bercly0b commented on src/pages/Auth/Auth.view.tsx
> +            setUserId(data.id);
вот тут не понял. зачем id запоминать в sate, если он ни где не используется дальше?

2022-01-16 14:06 UTC, bercly0b commented on src/pages/Auth/Auth.view.tsx
> +        authService.signup(getFormValues(formEl), updateUserId);
по хорошему бы значения формы хранить в стейте компонента и передавать его в `onSubmit` объектом.
у нас же реакт используется как абстракция над домом. а мы все равно пытаемся в дом ходить в обход абстракции..

2022-01-16 14:08 UTC, bercly0b requested changes
https://github.com/practicum-yandex/castle-rock/pull/8#discussion_r785446077

2022-01-16 15:09 UTC, rsungatovich commented on src/pages/Auth/Auth.view.tsx
> +            setUserId(data.id);
Думал может пригодиться в дальнейшем, раз возвращается))

2022-01-16 15:20 UTC, rsungatovich commented on src/pages/Auth/Auth.view.tsx
> +        authService.signup(getFormValues(formEl), updateUserId);
То есть каждое введенное значение в поле записывать в стейт компонента? Я просто иначе, не понял как их достать все сразу, не дергая элемент формы)

В ангуляр есть абстракция над формой, что-то типо форм групп. И очень удобно собирать все данные от туда.

2022-01-16 15:20 UTC, rsungatovich commented on src/pages/Auth/Auth.view.tsx
> +        authService.signup(getFormValues(formEl), updateUserId);
Пока смерджу так, потом поправляю - чтобы не блокировать работу.

2022-01-16 15:36 UTC, merged